<a href="https://colab.research.google.com/github/riyawakde16-art/Extra_task/blob/main/Extra_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
 fn

Saving Employee.csv to Employee.csv

In [8]:
filepath='/content/Employee.csv'
df=pd.read_csv(filepath)
df

,emp_id,employee_name,gender,age,department,job_role,email,phone_number,city,state,...,reward_points,employee_of_month_count,device_allocated,system_os,internet_access,shift_allowance,food_allowance,transport_allowance,bonus_eligibility,retirement_plan
0,1,Anjali Mehta,Male,45,HR,Software Engineer,anjali.mehta@company.com,8767705334,Hyderabad,Karnataka,...,328,6,Laptop,Linux,No,14,1654,184,Yes,No
1,2,Neha Kapoor,Female,50,Marketing,Marketing Analyst,neha.kapoor@company.com,7350849248,Bangalore,Maharashtra,...,384,12,Desktop,Linux,Yes,4554,551,88,No,Yes
2,3,Karan Shah,Male,32,IT,Data Analyst,karan.shah@company.com,7160671832,Bangalore,Karnataka,...,77,2,Desktop,Windows,No,572,2890,286,Yes,Yes
3,4,Rahul Patil,Male,37,Marketing,Data Analyst,rahul.patil@company.com,7284761706,Mumbai,Maharashtra,...,215,1,Laptop,Linux,Yes,4376,2092,1407,Yes,No
4,5,Riya Sharma,Male,29,Sales,Software Engineer,riya.sharma@company.com,9195229456,Hyderabad,Telangana,...,162,5,Laptop,Windows,No,3552,2184,113,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Arjun Singh,Female,45,Sales,Marketing Analyst,arjun.singh@company.com,9587558571,Hyderabad,Telangana,...,369,5,Desktop,Windows,Yes,2175,2588,107,Yes,No
996,997,Karan Shah,Female,52,Marketing,Marketing Analyst,karan.shah@company.com,8678871306,Delhi,Telangana,...,342,0,Desktop,Windows,No,2709,2240,1186,No,Yes
997,998,Rajesh Gupta,Female,22,Finance,Data Analyst,rajesh.gupta@company.com,7425066154,Delhi,Telangana,...,266,8,Laptop,Linux,No,702,2934,1120,No,No
998,999,Riya Sharma,Male,39,HR,Software Engineer,riya.sharma@company.com,7448862136,Hyderabad,Telangana,...,90,7,Laptop,Linux,Yes,1729,697,1299,Yes,Yes
999,1000,Rahul Patil,Male,31,Marketing,Sales Executive,rahul.patil@company.com,7646846464,Delhi,Karnataka,...,471,1,Laptop,Linux,Yes,154,662,1988,No,Yes

In [9]:
df.head()

,emp_id,employee_name,gender,age,department,job_role,email,phone_number,city,state,...,reward_points,employee_of_month_count,device_allocated,system_os,internet_access,shift_allowance,food_allowance,transport_allowance,bonus_eligibility,retirement_plan
0,1,Anjali Mehta,Male,45,HR,Software Engineer,anjali.mehta@company.com,8767705334,Hyderabad,Karnataka,...,328,6,Laptop,Linux,No,14,1654,184,Yes,No
1,2,Neha Kapoor,Female,50,Marketing,Marketing Analyst,neha.kapoor@company.com,7350849248,Bangalore,Maharashtra,...,384,12,Desktop,Linux,Yes,4554,551,88,No,Yes
2,3,Karan Shah,Male,32,IT,Data Analyst,karan.shah@company.com,7160671832,Bangalore,Karnataka,...,77,2,Desktop,Windows,No,572,2890,286,Yes,Yes
3,4,Rahul Patil,Male,37,Marketing,Data Analyst,rahul.patil@company.com,7284761706,Mumbai,Maharashtra,...,215,1,Laptop,Linux,Yes,4376,2092,1407,Yes,No
4,5,Riya Sharma,Male,29,Sales,Software Engineer,riya.sharma@company.com,9195229456,Hyderabad,Telangana,...,162,5,Laptop,Windows,No,3552,2184,113,No,No

In [10]:
df.tail()

,emp_id,employee_name,gender,age,department,job_role,email,phone_number,city,state,...,reward_points,employee_of_month_count,device_allocated,system_os,internet_access,shift_allowance,food_allowance,transport_allowance,bonus_eligibility,retirement_plan
995,996,Arjun Singh,Female,45,Sales,Marketing Analyst,arjun.singh@company.com,9587558571,Hyderabad,Telangana,...,369,5,Desktop,Windows,Yes,2175,2588,107,Yes,No
996,997,Karan Shah,Female,52,Marketing,Marketing Analyst,karan.shah@company.com,8678871306,Delhi,Telangana,...,342,0,Desktop,Windows,No,2709,2240,1186,No,Yes
997,998,Rajesh Gupta,Female,22,Finance,Data Analyst,rajesh.gupta@company.com,7425066154,Delhi,Telangana,...,266,8,Laptop,Linux,No,702,2934,1120,No,No
998,999,Riya Sharma,Male,39,HR,Software Engineer,riya.sharma@company.com,7448862136,Hyderabad,Telangana,...,90,7,Laptop,Linux,Yes,1729,697,1299,Yes,Yes
999,1000,Rahul Patil,Male,31,Marketing,Sales Executive,rahul.patil@company.com,7646846464,Delhi,Karnataka,...,471,1,Laptop,Linux,Yes,154,662,1988,No,Yes

In [12]:
df.shape

(1000, 79)

In [13]:
df.columns

Index(['emp_id', 'employee_name', 'gender', 'age', 'department', 'job_role',
       'email', 'phone_number', 'city', 'state', 'country', 'salary', 'bonus',
       'experience_years', 'joining_date', 'employment_type', 'shift',
       'work_mode', 'manager_name', 'team_name', 'performance_rating',
       'leaves_taken', 'sick_leaves', 'casual_leaves', 'project_count',
       'training_hours', 'promotion_status', 'last_promotion_year',
       'appraisal_score', 'attendance_percentage', 'overtime_hours',
       'education', 'university', 'graduation_year', 'marital_status',
       'blood_group', 'nationality', 'bank_name', 'account_number',
       'ifsc_code', 'emergency_contact_name', 'emergency_contact_number',
       'skills', 'certifications', 'languages_known', 'current_project',
       'project_deadline', 'project_status', 'previous_company',
       'notice_period', 'work_location', 'desk_number', 'employee_type',
       'insurance_status', 'pf_number', 'travel_frequency',
       'client_interaction_level', 'work_satisfaction', 'stress_level',
       'job_involvement', 'leadership_score', 'communication_score',
       'technical_score', 'innovation_score', 'teamwork_score',
       'discipline_score', 'absent_days', 'late_marks', 'warnings',
       'reward_points', 'employee_of_month_count', 'device_allocated',
       'system_os', 'internet_access', 'shift_allowance', 'food_allowance',
       'transport_allowance', 'bonus_eligibility', 'retirement_plan'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 79 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   emp_id                    1000 non-null   int64
 1   employee_name             1000 non-null   object
 2   gender                    1000 non-null   object
 3   age                       1000 non-null   int64
 4   department                1000 non-null   object
 5   job_role                  1000 non-null   object
 6   email                     1000 non-null   object
 7   phone_number              1000 non-null   int64
 8   city                      1000 non-null   object
 9   state                     1000 non-null   object
 10  country                   1000 non-null   object
 11  salary                    1000 non-null   float64
 12  bonus                     1000 non-null   float64
 13  experience_years          1000 non-null   int64
 14  joining_date              1000 non-null   object
 15  employment_type           1000 non-null   object
 16  shift                     1000 non-null   object
 17  work_mode                 1000 non-null   object
 18  manager_name              1000 non-null   object
 19  team_name                 1000 non-null   object
 20  performance_rating        1000 non-null   float64
 21  leaves_taken              1000 non-null   int64
 22  sick_leaves               1000 non-null   int64
 23  casual_leaves             1000 non-null   int64
 24  project_count             1000 non-null   int64
 25  training_hours            1000 non-null   int64
 26  promotion_status          1000 non-null   object
 27  last_promotion_year       1000 non-null   int64
 28  appraisal_score           1000 non-null   float64
 29  attendance_percentage     1000 non-null   float64
 30  overtime_hours            1000 non-null   int64
 31  education                 1000 non-null   object
 32  university                1000 non-null   object
 33  graduation_year           1000 non-null   int64
 34  marital_status            1000 non-null   object
 35  blood_group               1000 non-null   object
 36  nationality               1000 non-null   object
 37  bank_name                 1000 non-null   object
 38  account_number            1000 non-null   int64
 39  ifsc_code                 1000 non-null   object
 40  emergency_contact_name    1000 non-null   object
 41  emergency_contact_number  1000 non-null   int64
 42  skills                    1000 non-null   object
 43  certifications            669 non-null    object
 44  languages_known           1000 non-null   object
 45  current_project           1000 non-null   object
 46  project_deadline          1000 non-null   object
 47  project_status            1000 non-null   object
 48  previous_company          757 non-null    object
 49  notice_period             1000 non-null   object
 50  work_location             1000 non-null   object
 51  desk_number               1000 non-null   object
 52  employee_type             1000 non-null   object
 53  insurance_status          1000 non-null   object
 54  pf_number                 1000 non-null   int64
 55  travel_frequency          1000 non-null   object
 56  client_interaction_level  1000 non-null   object
 57  work_satisfaction         1000 non-null   object
 58  stress_level              1000 non-null   object
 59  job_involvement           1000 non-null   object
 60  leadership_score          1000 non-null   int64
 61  communication_score       1000 non-null   int64
 62  technical_score           1000 non-null   int64
 63  innovation_score          1000 non-null   int64
 64  teamwork_score            1000 non-null   int64
 65  discipline_score          1000 non-null   int64
 66  absent_days               1000 non-null   int64
 67  late_marks                1000 non-null   int64
 68  warnings                  1000 non-null   int64
 69  reward_points             1000 non-null   int64
 70  employee_of_month_count   1000 non-null   int64
 71  device_allocated          1000 non-null   object
 72  system_os                 1000 non-null   object
 73  internet_access           1000 non-null   object
 74  shift_allowance           1000 non-null   int64
 75  food_allowance            1000 non-null   int64
 76  transport_allowance       1000 non-null   int64
 77  bonus_eligibility         1000 non-null   object
 78  retirement_plan           1000 non-null   object
dtypes: float64(5), int64(29), object(45)
memory usage: 617.3+ KB

In [15]:
df.describe()

,emp_id,age,phone_number,salary,bonus,experience_years,performance_rating,leaves_taken,sick_leaves,casual_leaves,...,teamwork_score,discipline_score,absent_days,late_marks,warnings,reward_points,employee_of_month_count,shift_allowance,food_allowance,transport_allowance
count,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.00000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,40.513000,8.467767e+09,74778.680830,12449.28025,5.51800,3.985140,14.971000,5.105000,4.855000,...,3.044000,2.999000,10.059000,4.965000,1.507000,242.593000,6.033000,2460.658000,1491.603000,976.574000
std,288.819436,11.295549,8.584466e+08,26226.870149,4348.94860,2.89967,0.578064,8.906823,3.213768,3.157522,...,1.402152,1.410315,6.174272,3.109573,1.134565,142.318023,3.618979,1480.784199,871.103282,583.985873
min,1.000000,21.000000,7.008096e+09,30012.900000,5001.90000,1.00000,3.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000,1.000000
25%,250.750000,31.000000,7.751988e+09,51762.727500,8594.49000,3.00000,3.480000,7.000000,2.000000,2.000000,...,2.000000,2.000000,5.000000,2.000000,0.000000,118.750000,3.000000,1122.000000,743.750000,457.500000
50%,500.500000,41.000000,8.406426e+09,74776.765000,12694.18000,6.00000,3.975000,15.000000,5.000000,5.000000,...,3.000000,3.000000,10.000000,5.000000,1.000000,235.500000,6.000000,2485.500000,1463.000000,987.500000
75%,750.250000,50.000000,9.182150e+09,98231.090000,16125.45250,8.00000,4.490000,23.000000,8.000000,8.000000,...,4.000000,4.000000,16.000000,8.000000,3.000000,368.250000,9.000000,3733.000000,2271.250000,1478.500000
max,1000.000000,60.000000,9.997849e+09,119968.770000,19950.58000,10.00000,5.000000,30.000000,10.000000,10.000000,...,5.000000,5.000000,20.000000,10.000000,3.000000,500.000000,12.000000,4984.000000,3000.000000,2000.000000

In [16]:
df.dtypes

emp_id                  int64
employee_name          object
gender                 object
age                     int64
department             object
                        ...
shift_allowance         int64
food_allowance          int64
transport_allowance     int64
bonus_eligibility      object
retirement_plan        object
Length: 79, dtype: object

In [17]:
df.isnull().sum()

emp_id                 0
employee_name          0
gender                 0
age                    0
department             0
                      ..
shift_allowance        0
food_allowance         0
transport_allowance    0
bonus_eligibility      0
retirement_plan        0
Length: 79, dtype: int64

In [18]:
df.nunique()

emp_id                 1000
employee_name            10
gender                    2
age                      40
department                5
                       ...
shift_allowance         917
food_allowance          864
transport_allowance     778
bonus_eligibility         2
retirement_plan           2
Length: 79, dtype: int64

In [19]:
df.sample(5)

,emp_id,employee_name,gender,age,department,job_role,email,phone_number,city,state,...,reward_points,employee_of_month_count,device_allocated,system_os,internet_access,shift_allowance,food_allowance,transport_allowance,bonus_eligibility,retirement_plan
440,441,Arjun Singh,Male,25,IT,Accountant,arjun.singh@company.com,7459841170,Pune,Karnataka,...,188,10,Desktop,Linux,Yes,2143,541,172,Yes,No
537,538,Karan Shah,Male,42,IT,HR Manager,karan.shah@company.com,9849434470,Hyderabad,Maharashtra,...,195,4,Desktop,Linux,No,1933,1344,227,Yes,Yes
31,32,Amit Verma,Female,32,HR,Data Analyst,amit.verma@company.com,8288095905,Bangalore,Karnataka,...,232,10,Desktop,Windows,No,4235,265,289,No,Yes
903,904,Amit Verma,Female,46,Finance,Data Analyst,amit.verma@company.com,8468027112,Delhi,Karnataka,...,481,4,Desktop,Windows,No,4205,1133,532,No,No
614,615,Riya Sharma,Female,37,HR,Accountant,riya.sharma@company.com,8852305082,Pune,Karnataka,...,120,8,Desktop,Linux,Yes,4265,2976,803,No,No

In [20]:
df.value_counts()

emp_id  employee_name  gender  age  department  job_role           email                     phone_number  city       state        country  salary     bonus     experience_years  joining_date  employment_type  shift  work_mode  manager_name    team_name  performance_rating  leaves_taken  sick_leaves  casual_leaves  project_count  training_hours  promotion_status  last_promotion_year  appraisal_score  attendance_percentage  overtime_hours  education  university      graduation_year  marital_status  blood_group  nationality  bank_name  account_number  ifsc_code    emergency_contact_name  emergency_contact_number  skills       certifications  languages_known  current_project  project_deadline  project_status  previous_company  notice_period  work_location  desk_number  employee_type  insurance_status  pf_number  travel_frequency  client_interaction_level  work_satisfaction  stress_level  job_involvement  leadership_score  communication_score  technical_score  innovation_score  teamwork_score  discipline_score  absent_days  late_marks  warnings  reward_points  employee_of_month_count  device_allocated  system_os  internet_access  shift_allowance  food_allowance  transport_allowance  bonus_eligibility  retirement_plan
999     Riya Sharma    Male    39   HR          Software Engineer  riya.sharma@company.com   7448862136    Hyderabad  Telangana    India    49605.54   9308.17   5                 2024-10-18    Full-time        Night  Hybrid     Sneha Kulkarni  Team 9     3.83                12            5            6              7              58              Yes               2015                 3.22             84.91                  33              BTech      XYZ University  2015             Married         A+           Indian       SBI        45040414        SBIN0001234  Arjun Singh             9302039893                Salesforce   Azure           English,Hindi    Project 1        2026-12-07        Completed       Infosys           30 days        Pune           D-39         Permanent      Active            151487     Medium            High                      Poor               Low           Low              1                 2                    1                1                 3               4                 7            3           3         90             7                        Laptop            Linux      Yes              1729             697             1299                 Yes                Yes                1
4       Rahul Patil    Male    37   Marketing   Data Analyst       rahul.patil@company.com   7284761706    Mumbai     Maharashtra  India    99149.11   10028.13  4                 2020-06-28    Full-time        Night  Hybrid     Sneha Kulkarni  Team 10    3.17                15            3            2              4              94              Yes               2016                 4.33             75.59                  27              BCom       XYZ University  2014             Married         O+           Indian       SBI        58610685        SBIN0001234  Anjali Mehta            8629059518                Python, SQL  AWS             English,Hindi    Project 1        2026-08-30        Ongoing         Wipro             30 days        Bangalore      D-70         Contract       Inactive          157331     Low               Low                       Poor               Low           Low              3                 1                    3                2                 1               2                 10           9           2         215            1                        Laptop            Linux      Yes              4376             2092            1407                 Yes                No                 1
5       Riya Sharma    Male    29   Sales       Software Engineer  riya.sharma@company.com   9195229456    Hyderabad  Telangana    India    97931.80   18688.48  2                 2025-06-16    Full-time        Day    Hybrid     Neha Kapoor     Team 6     4.38                8             9            1              14             39              No                2018                 4.64             93.56                  45              BCom       XYZ University  2021             Married         A+           Indian       SBI        77245648        SBIN0001234  Priya Deshmukh          8814524797                Salesforce   AWS             English          Project 6        2026-11-22        Completed       TCS               30 days        Delhi          D-71         Contract       Inactive          710545     High              High                      Poor               Medium        High             4                 3                    5                1                 4               3                 3            10          0         162            5                        Laptop            Windows    No               3552             2184            113                  No                 No                 1
8       Karan Shah     Male    25   Sales       HR Manager         karan.shah@company.com    7117009794    Bangalore  Delhi        India    119283.89  16568.65  6                 2020-02-25    Part-time        Night  Hybrid     Sneha Kulkarni  Team 7     3.12                3             3            9              2              15              No                2020                 4.54             79.16                  35              BTech      XYZ University  2013             Married         A+           Indian       SBI        32248981        SBIN0001234  Priya Deshmukh          9474130162                Excel, HR    Azure           English          Project 2        2026-12-20        Completed       Wipro             60 days        Bangalore      D-62         Contract       Inactive          450041     Low               High                      Poor               Medium        Low              2                 5                    5                2                 2               3                 14           2           3         83             6                        Laptop            Windows    No               3131             1229            550                  No                 Yes                1
9       Rajesh Gupta   Male    41   Marketing   Sales Executive    rajesh.gupta@company.com  8810449849    Pune       Maharashtra  India    61716.88   17384.05  3                 2024-04-13    Full-time        Night  Remote     Amit Verma      Team 3     4.59                16            2            10             2              36              No                2021                 3.04             90.79                  2               BTech      XYZ University  2013             Single          O+           Indian       SBI        58072689        SBIN0001234  Sneha Kulkarni          7293123090                Salesforce   AWS             English,Hindi    Project 9        2026-07-29        Completed       TCS               60 days        Mumbai         D-59         Contract       Inactive          586743     High              Low                       Poor               Low           Low              5                 3                    2                5                 5               5                 18           10          2         76             8                        Desktop           Linux      Yes              4143             286             1299                 No                 Yes                1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
29      Riya Sharma    Female  45   Finance     HR Manager         riya.sharma@company.com   9578775871    Bangalore  Maharashtra  India    74659.70   5342.75   10                2021-08-29    Full-time        Day    Hybrid     Rahul Patil     Team 2     4.28                12            0            1              11             73              No                2019                 3.64             72.63                  24              BTech      XYZ University  2022             Married         B+           Indian       SBI        64017219        SBIN0001234  Amit Verma              7636246322                Python, SQL  AWS             English          Project 1        2026-09-17        Ongoing         TCS               30 days        Mumbai         D-40         Permanent      Active            552821     Low               Low                       Average            High          Low              5                 2                    5                1                 1               5                 6            10          2         418            2                        Desktop           Linux      Yes              2099             766             798                  Yes                No                 1
27      Karan Shah     Male    40   Marketing   Data Analyst       karan.shah@company.com    9014655946    Hyderabad  Maharashtra  India    32486.09   13605.05  7                 2018-05-29    Full-time        Night  Remote     Riya Sharma     Team 6     4.85                30            3            2              14             45              No                2023                 3.21             95.01                  29              BTech      XYZ University  2013             Single          O+           Indian       SBI        36091064        SBIN0001234  Rahul Patil             9282195952                Salesforce   AWS             English          Project 7        2026-11-02        Completed       Infosys           30 days        Mumbai         D-66         Contract       Active            656950     Medium            High                      Average            Medium        Medium           4                 3                    1                5                 2               3                 13           4           3         62             2                        Desktop           Linux      No               1634             1378            1514                 Yes                Yes                1
23      Riya Sharma    Female  50   Sales       Data Analyst       riya.sharma@company.com   8367462298    Mumbai     Karnataka    India    52193.74   17553.48  10                2021-09-18    Part-time        Day    Hybrid     Rahul Patil     Team 6     4.71                0             6            1              12             73              No                2024                 4.42             84.67                  14              BCom       XYZ University  2015             Married         B+           Indian       SBI        67438675        SBIN0001234  Sneha Kulkarni          7292714959                Python, SQL  AWS             English          Project 8        2026-07-26        Ongoing         Infosys           30 days        Bangalore      D-73         Permanent      Inactive          787354     Medium            Low                       Poor               Medium        Medium           2                 4                    1                3                 3               2                 13           0           0         245            6                        Laptop            Linux      Yes              4242             809             1228                 No                 No                 1
22      Amit Verma     Male    41   HR          Software Engineer  amit.verma@company.com    8974151683    Mumbai     Maharashtra  India    63002.51   11472.36  5                 2026-03-14    Full-time        Night  Hybrid     Karan Shah      Team 4     3.74                16            9            6              15             97              Yes               2021                 4.22             96.58                  46              BTech      XYZ University  2017             Single          B+           Indian       SBI        57688153        SBIN0001234  Priya Deshmukh          8660368118                Salesforce   Azure           English          Project 10       2027-01-17        Ongoing         Wipro             30 days        Pune           D-92         Permanent      Inactive          718061     Low               Low                       Poor               Low           Low              2                 4                    3                1                 3               2                 6            6           0         309            2                        Desktop           Windows    Yes              1006             1462            1044                 Yes                Yes                1
19      Amit Verma     Male    36   Sales       Accountant         amit.verma@company.com    8072835081    Delhi      Telangana    India    56580.52   8204.68   3                 2020-11-30    Part-time        Night  Hybrid     Rahul Patil     Team 5     3.51                27            9            6              10             38              No                2017                 4.21             92.15                  13              BCom       XYZ University  2022             Married         B+           Indian       SBI        98620626        SBIN0001234  Neha Kapoor             7128430222                Python, SQL  AWS             English,Hindi    Project 2        2026-07-20        Completed       TCS               30 days        Delhi          D-25         Contract       Active            668508     Medium            Medium                    Poor               Medium        Low              4                 3                    5                1                 2               5                 6            9           1         195            8                        Laptop            Windows    Yes              688              2644            585                  Yes                No                 1
Name: count, Length: 491, dtype: int64